[ADD] Job failure on cleanliness error

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -22,11 +22,13 @@ jobs:
         with:
           fetch-depth: 0
       - name: Find unwanted files
-        run: find . -regextype posix-extended -regex '.*\.(a|o|so|gcda|gcno|gcov)' -exec echo "::error file={},title="Unwanted file detected"::{}" \;
+        run: find . -regextype posix-extended -regex '.*\.(~.a|o|so|gcda|gcno|gcov)' -exec echo "::error file={},title="Unwanted file detected"::{}" \;
       - name: Find files in tmp
         run: find . -path '*/tmp/*' -exec echo "::error file={},title="Unwanted file detected"::{}" \;
       - name: Find pain_au_chocolat files
-        run: find . -iname "*pain_au_chocolat*" -o -name "*~" -exec echo "::error file={},title="Unwanted file detected"::{}" \;
+        run: find . -iname "*pain_au_chocolat*" -exec echo "::error file={},title="Unwanted file detected"::{}" \;
+      - name: Exit if file is found
+        run: find . -regextype posix-extended -regex '.*\.(a|o|so|gcda|gcno|gcov)' -o -path '*/tmp/*' -o -iname "*pain_au_chocolat*" | grep -q . && exit 1
   check_program_compilation:
     name: Check program compilation
     runs-on: ubuntu-latest
