[ADD] Exit if executables not found

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -45,6 +45,10 @@ jobs:
         run: make
       - name: Clean execution
         run: make clean
+      - name: Test executables presence
+        run: IFS=',' read -r -a array <<< ${{ env.EXECUTABLES }} ; for value in ${array[@]} ; do find . -executable -name "${value}" | grep -q . || echo "::error title="Executable not found"::${value}" ; done
+      - name: Exit if executable not found
+        run: IFS=',' read -r -a array <<< ${{ env.EXECUTABLES }} ; for value in ${array[@]} ; do find . -executable -name "${value}" | grep -q . || exit 1 ; done
   run_tests:
     name: Run tests
     runs-on: ubuntu-latest
